# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YSPathView' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YSPathView
  pod 'YSPath'
#  pod 'YSPath', :path => "../"
#  pod 'YSPath', :source => "https://github.com/yangjiaxuan/YSSpec.git"
  
  target 'YSPathViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YSPathViewUITests' do
    # Pods for testing
  end

end
